# questa container fa uso di una immagine generica di nginx, 
# senza usare quella di baltig dell'INFN.

version: "3.9"

services:

  revproxy:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx_docker_revproxy/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_docker_revproxy/scripts/:/etc/nginx/njs/
      - ./nginx_docker_revproxy/certificates_for_https/:/etc/nginx/certs/
    ports:
      - "8081:443"

  opa:
    image: openpolicyagent/opa:0.39.0-istio
    volumes:
      - ./opa/policy.rego:/etc/opa/policy.rego
      - ./opa/data.json:/etc/opa/data.json
      - ./opa/config.yaml:/etc/opa/config.yaml
    command:
      - run
      - --server
      - /etc/opa/policy.rego
      - /etc/opa/data.json
      - -c
      - /etc/opa/config.yaml

  service_server:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx_docker_webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_docker_webserver/src/:/usr/share/nginx/html/